# Generated by Django 5.2.14 on 2026-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_customer_email_quotation_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='excludes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='includes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
