# Generated by Django 5.2.14 on 2026-05-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_delivery_terms_quotation_excludes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='to_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
