# Generated by Django 5.2.14 on 2026-05-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_quotation_company_description_quotation_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
