# Generated by Django 5.2.14 on 2026-05-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='customer_name',
            new_name='material',
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitted_by_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitted_by_name',
            field=models.CharField(default='روفانا تريد', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitted_to_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitted_to_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity',
            field=models.CharField(default='30 يوم', max_length=100),
        ),
    ]
