# Generated by Django 5.2.14 on 2026-05-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_rename_customer_name_quotation_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='vat_rate',
            field=models.FloatField(default=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='warning_note',
            field=models.TextField(default='الأسعار تقديرية وتخضع لأسعار المواد وقت التنفيذ وسعر الصرف.'),
        ),
        migrations.CreateModel(
            name='QuoteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='قسم جديد', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quotations.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(default='عدد', max_length=50)),
                ('unit_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotesection')),
            ],
        ),
    ]
