# Generated by Django 5.2.14 on 2026-05-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotation_vat_rate_quotation_warning_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='quotesection',
            options={'ordering': ['sort_order']},
        ),
    ]
