# Generated by Django 5.2.14 on 2026-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_quotation_options_alter_quoteitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_terms',
            field=models.TextField(default='مدة التصنيع: تحدد عند الطلب\n    التسليم: موقع العميل\n    يشمل التغليف والشحن الداخلي'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='excluded_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='included_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(default='40% دفعة مقدمة عند تأكيد الطلب\n    40% عند التسليم للموقع\n    20% بعد إتمام التركيب والقبول'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='submitted_by_signature',
            field=models.CharField(default='روفانا تريد', max_length=255),
        ),
    ]
