# Generated by Django 5.2.14 on 2026-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_quotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
